/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import { styled } from '@mui/material/styles';
import StepIcon from 'src/components/StepIcon/StepIcon';
import { StepperProps } from 'src/types';
const Stepper1 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    width: '100%',
    height: `52px`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
});
const Pending = styled('div')(({ theme }) => ({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `11px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    position: `absolute`,
    left: `4px`,
    top: `36px`,
}));
const Sent = styled('div')(({ theme }) => ({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(217, 140, 51, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `11px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    position: `absolute`,
    left: `127px`,
    top: `36px`,
}));
const Underwriting = styled('div')(({ theme }) => ({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(73, 80, 87, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `11px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    position: `absolute`,
    left: `219px`,
    top: `36px`,
}));
const NeedMoreInfo = styled('div')(({ theme }) => ({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(73, 80, 87, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `11px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    position: `absolute`,
    left: `325px`,
    top: `36px`,
}));
const Frame186 = styled('div')({
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `388px`,
    height: `24px`,
    left: `13px`,
    top: `0px`,
});
const StepIcon1 = styled(StepIcon)(({ theme }) => ({
    width: `24px`,
    height: `24px`,
    margin: `0px`,
}));
const Frame188 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 4px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Rectangle1 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(217, 140, 51, 1)`,
    borderRadius: `1px`,
    height: `2px`,
    width: `86px`,
    margin: `0px`,
}));
const StepIcon2 = styled(StepIcon)(({ theme }) => ({
    width: `24px`,
    height: `24px`,
    margin: `0px`,
}));
const Frame187 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 0px 0px 4px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Rectangle2 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(222, 226, 230, 1)`,
    borderRadius: `1px`,
    height: `2px`,
    width: `86px`,
    margin: `0px`,
}));
const StepIcon3 = styled(StepIcon)(({ theme }) => ({
    width: `24px`,
    height: `24px`,
    margin: `0px`,
}));
const Rectangle3 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(222, 226, 230, 1)`,
    borderRadius: `1px`,
    width: `90px`,
    height: `2px`,
    margin: `0px`,
}));
const StepIcon4 = styled(StepIcon)(({ theme }) => ({
    width: `24px`,
    height: `24px`,
    margin: `0px`,
}));
function Stepper(props) {
    return (React.createElement(Stepper1, { className: props.className },
        React.createElement(Pending, null, `Pending`),
        React.createElement(Sent, null, `Sent`),
        React.createElement(Underwriting, null, `Underwriting`),
        React.createElement(NeedMoreInfo, null, `Need more info.`),
        React.createElement(Frame186, null,
            React.createElement(StepIcon1, null),
            React.createElement(Frame188, null,
                React.createElement(Rectangle1, null)),
            React.createElement(StepIcon2, null),
            React.createElement(Frame187, null,
                React.createElement(Rectangle2, null)),
            React.createElement(StepIcon3, null),
            React.createElement(Rectangle3, null),
            React.createElement(StepIcon4, null))));
}
export default Stepper;
//# sourceMappingURL=Stepper.js.map