/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import VectorImage from 'src/assets/images/Row_Vector.png';
import Vector1Image from 'src/assets/images/Row_Vector_1.png';
import Vector2Image from 'src/assets/images/Row_Vector_2.png';
import Vector3Image from 'src/assets/images/Row_Vector_3.png';
import Vector4Image from 'src/assets/images/Row_Vector_4.png';
import { styled } from '@mui/material/styles';
import Cell from 'src/components/Cell/Cell';
import Badge1 from 'src/components/Badge1/Badge1';
import { RowProps } from 'src/types';
const RowHeader = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(255, 255, 255, 1)`,
    border: `1px solid rgba(241, 243, 245, 1)`,
    borderRadius: `24px 24px 0px 0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    width: '100%',
    justifyContent: `space-between`,
    alignItems: `center`,
    padding: `16px 24px`,
    boxSizing: `border-box`,
    height: 'auto',
}));
const Frame28 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell1 = styled(Cell)(({ theme }) => ({
    width: `200px`,
    margin: `0px`,
}));
const Cell2 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame27 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-end`,
    alignItems: `center`,
    padding: `0px 100px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell3 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px`,
}));
const Cell4 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Cell5 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame281 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell6 = styled(Cell)(({ theme }) => ({
    width: `200px`,
    margin: `0px`,
}));
const Cell7 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame271 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px 100px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell8 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px`,
}));
const Cell9 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame29 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `80px`,
    margin: `0px 0px 0px 96px`,
});
const Badge2 = styled(Badge1)(({ theme }) => ({
    margin: `0px`,
}));
const Frame282 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell10 = styled(Cell)(({ theme }) => ({
    width: `200px`,
    margin: `0px`,
}));
const Cell11 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame272 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px 100px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell12 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px`,
}));
const Cell13 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame291 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `80px`,
    margin: `0px 0px 0px 96px`,
});
const Badge3 = styled(Badge1)(({ theme }) => ({
    margin: `0px`,
}));
const Frame283 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell14 = styled(Cell)(({ theme }) => ({
    width: `200px`,
    margin: `0px`,
}));
const Cell15 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Group = styled('div')({
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `12.76px`,
    height: `16.01px`,
    left: `194px`,
    top: `13px`,
});
const Vector = styled('img')({
    height: `16.01px`,
    width: `12.76px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
const Vector1 = styled('img')({
    height: `16.01px`,
    width: `12.76px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
const Vector2 = styled('img')({
    height: `3.57px`,
    width: `0px`,
    position: `absolute`,
    left: `10px`,
    top: `9px`,
});
const Vector3 = styled('img')({
    height: `3.57px`,
    width: `0.09px`,
    position: `absolute`,
    left: `8px`,
    top: `9px`,
});
const Vector4 = styled('img')({
    height: `3.57px`,
    width: `0px`,
    position: `absolute`,
    left: `6px`,
    top: `9px`,
});
const Frame31 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 100px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame32 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame273 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell16 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px`,
}));
const Cell17 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame292 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `80px`,
    margin: `0px 0px 0px 96px`,
});
const Badge4 = styled(Badge1)(({ theme }) => ({
    margin: `0px`,
}));
const Frame284 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell18 = styled(Cell)(({ theme }) => ({
    width: `200px`,
    margin: `0px`,
}));
const Cell19 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame274 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px 100px 0px 0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Cell20 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px`,
}));
const Cell21 = styled(Cell)(({ theme }) => ({
    width: `80px`,
    margin: `0px 0px 0px 96px`,
}));
const Frame293 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `80px`,
    margin: `0px 0px 0px 96px`,
});
const Badge5 = styled(Badge1)(({ theme }) => ({
    margin: `0px`,
}));
function Row(props) {
    return (React.createElement(RowHeader, { className: props.className },
        React.createElement(Frame28, null,
            React.createElement(Cell1, null),
            React.createElement(Cell2, null)),
        React.createElement(Frame27, null,
            React.createElement(Cell3, null),
            React.createElement(Cell4, null),
            React.createElement(Cell5, null)),
        false && (React.createElement(Frame281, null,
            React.createElement(Cell6, null),
            React.createElement(Cell7, null))),
        false && (React.createElement(Frame271, null,
            React.createElement(Cell8, null),
            React.createElement(Cell9, null),
            React.createElement(Frame29, null,
                React.createElement(Badge2, null)))),
        false && (React.createElement(Frame282, null,
            React.createElement(Cell10, null),
            React.createElement(Cell11, null))),
        false && (React.createElement(Frame272, null,
            React.createElement(Cell12, null),
            React.createElement(Cell13, null),
            React.createElement(Frame291, null,
                React.createElement(Badge3, null)))),
        false && (React.createElement(Frame283, null,
            React.createElement(Cell14, null),
            React.createElement(Cell15, null),
            React.createElement(Group, null,
                React.createElement(Vector, { src: VectorImage, loading: "lazy", alt: 'Vector' }),
                React.createElement(Vector1, { src: Vector1Image, loading: "lazy", alt: 'Vector' }),
                React.createElement(Vector2, { src: Vector2Image, loading: "lazy", alt: 'Vector' }),
                React.createElement(Vector3, { src: Vector3Image, loading: "lazy", alt: 'Vector' }),
                React.createElement(Vector4, { src: Vector4Image, loading: "lazy", alt: 'Vector' })))),
        false && (React.createElement(Frame31, null,
            React.createElement(Frame32, null,
                React.createElement(Frame273, null,
                    React.createElement(Cell16, null),
                    React.createElement(Cell17, null),
                    React.createElement(Frame292, null,
                        React.createElement(Badge4, null)))))),
        false && (React.createElement(Frame284, null,
            React.createElement(Cell18, null),
            React.createElement(Cell19, null))),
        false && (React.createElement(Frame274, null,
            React.createElement(Cell20, null),
            React.createElement(Cell21, null),
            React.createElement(Frame293, null,
                React.createElement(Badge5, null))))));
}
export default Row;
//# sourceMappingURL=Row.js.map