/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import TopographyImage from 'src/assets/images/RedeemMilesModal_Topography.png';
import HeroiconsMiniSparkleImage from 'src/assets/images/RedeemMilesModal_heroicons_mini_sparkles.svg';
import HeroiconsOutlineXMarImage from 'src/assets/images/RedeemMilesModal_heroicons_outline_x_mark.svg';
import HeroiconsMiniSparkle1Image from 'src/assets/images/RedeemMilesModal_heroicons_mini_sparkles_1.svg';
import HeroiconsOutlineXMar1Image from 'src/assets/images/RedeemMilesModal_heroicons_outline_x_mark_1.svg';
import { styled } from '@mui/material/styles';
import Input1 from 'src/components/Input1/Input1';
import Button1 from 'src/components/Button1/Button1';
import { RedeemMilesModalProps } from 'src/types';
const Property1Default = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(255, 255, 255, 1)`,
    border: `1px solid rgba(241, 243, 245, 1)`,
    borderRadius: `24px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    width: '100%',
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `40px`,
    boxSizing: `border-box`,
    height: 'auto',
}));
const Topography = styled('img')({
    height: `150px`,
    width: `465px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
const Frame139 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Frame124 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Frame188 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `space-between`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Frame190 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame189 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(251, 244, 235, 1)`,
    borderRadius: `100px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `6px`,
    boxSizing: `border-box`,
    margin: `0px`,
}));
const HeroiconsMiniSparkle = styled('img')({
    height: `auto`,
    width: `15px`,
    margin: `0px`,
});
const RedeemYourMiles = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `18px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    margin: `0px 0px 0px 12px`,
}));
const HeroiconsOutlineXMar = styled('img')({
    height: `auto`,
    width: `24px`,
    margin: `0px`,
});
const LoremIpsumDolorSitAm = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(173, 181, 189, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `8px 0px 0px 0px`,
}));
const Frame38 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `40px 0px 0px 0px`,
});
const Frame186 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Input2 = styled(Input1)(({ theme }) => ({
    flex: `1`,
    margin: `0px`,
}));
const Input3 = styled(Input1)(({ theme }) => ({
    flex: `1`,
    margin: `0px 0px 0px 24px`,
}));
const Input4 = styled(Input1)(({ theme }) => ({
    alignSelf: `stretch`,
    margin: `24px 0px 0px 0px`,
}));
const Input5 = styled(Input1)(({ theme }) => ({
    alignSelf: `stretch`,
    margin: `24px 0px 0px 0px`,
}));
const Input6 = styled(Input1)(({ theme }) => ({
    alignSelf: `stretch`,
    margin: `24px 0px 0px 0px`,
}));
const Frame1241 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `40px 0px 0px 0px`,
});
const Frame1881 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `space-between`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Frame1901 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame1891 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(251, 244, 235, 1)`,
    borderRadius: `100px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `6px`,
    boxSizing: `border-box`,
    margin: `0px`,
}));
const HeroiconsMiniSparkle1 = styled('img')({
    height: `auto`,
    width: `15px`,
    margin: `0px`,
});
const RedeemYourMiles1 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `18px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    margin: `0px 0px 0px 12px`,
}));
const HeroiconsOutlineXMar1 = styled('img')({
    height: `auto`,
    width: `24px`,
    margin: `0px`,
});
const Frame192 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `40px 0px 0px 0px`,
});
const Frame191 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `385px`,
    margin: `0px`,
});
const YourCurrentMilesBalaSpan1 = styled('span')(({ theme }) => ({
    whiteSpace: `pre-wrap`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
}));
const YourCurrentMilesBalaSpan2 = styled('span')(({ theme }) => ({
    whiteSpace: `pre-wrap`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `700`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
}));
const YourCurrentMilesBala = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: 'unset',
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    flex: `1`,
    margin: `0px`,
}));
const Frame381 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `385px`,
    margin: `8px 0px 0px 0px`,
});
const Button2 = styled(Button1)(({ theme }) => ({
    margin: `0px`,
}));
const Input7 = styled(Input1)(({ theme }) => ({
    flex: `1`,
    margin: `0px 0px 0px -1px`,
}));
const Button3 = styled(Button1)(({ theme }) => ({
    margin: `0px 0px 0px -1px`,
}));
const YourNewBalanceWillBe = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(134, 142, 150, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `11px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `8px 0px 0px 0px`,
}));
const Frame184 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-end`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `40px 0px 0px 0px`,
});
const Button4 = styled(Button1)(({ theme }) => ({
    flex: `1`,
    margin: `0px`,
}));
function RedeemMilesModal(props) {
    return (React.createElement(Property1Default, { className: props.className },
        React.createElement(Topography, { src: TopographyImage, loading: "lazy", alt: 'Topography' }),
        React.createElement(Frame139, null,
            React.createElement(Frame124, null,
                React.createElement(Frame188, null,
                    React.createElement(Frame190, null,
                        React.createElement(Frame189, null,
                            React.createElement(HeroiconsMiniSparkle, { src: HeroiconsMiniSparkleImage, loading: "lazy", alt: 'heroicons-mini/sparkles' })),
                        React.createElement(RedeemYourMiles, null, `Redeem your miles`)),
                    React.createElement(HeroiconsOutlineXMar, { src: HeroiconsOutlineXMarImage, loading: "lazy", alt: 'heroicons-outline/x-mark' })),
                React.createElement(LoremIpsumDolorSitAm, null, `Lorem ipsum dolor sit amet consectetur `)),
            React.createElement(Frame38, null,
                React.createElement(Frame186, null,
                    React.createElement(Input2, null),
                    React.createElement(Input3, null)),
                React.createElement(Input4, null),
                React.createElement(Input5, null),
                React.createElement(Input6, null)),
            false && (React.createElement(Frame1241, null,
                React.createElement(Frame1881, null,
                    React.createElement(Frame1901, null,
                        React.createElement(Frame1891, null,
                            React.createElement(HeroiconsMiniSparkle1, { src: HeroiconsMiniSparkle1Image, loading: "lazy", alt: 'heroicons-mini/sparkles' })),
                        React.createElement(RedeemYourMiles1, null, `Redeem your miles`)),
                    React.createElement(HeroiconsOutlineXMar1, { src: HeroiconsOutlineXMar1Image, loading: "lazy", alt: 'heroicons-outline/x-mark' })))),
            false && (React.createElement(Frame192, null,
                React.createElement(Frame191, null,
                    React.createElement(YourCurrentMilesBala, null,
                        React.createElement(YourCurrentMilesBalaSpan1, null, `Your current miles balance is `),
                        React.createElement(YourCurrentMilesBalaSpan2, null, `6,000.`))),
                React.createElement(Frame381, null,
                    React.createElement(Button2, null),
                    React.createElement(Input7, null),
                    React.createElement(Button3, null)),
                React.createElement(YourNewBalanceWillBe, null, `Your new balance will be 5900.`)))),
        React.createElement(Frame184, null,
            React.createElement(Button4, null))));
}
export default RedeemMilesModal;
//# sourceMappingURL=RedeemMilesModal.js.map