/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import { styled } from '@mui/material/styles';
import ReadOnlyFormItem from 'src/components/ReadOnlyFormItem/ReadOnlyFormItem';
import { ReadOnlyFormProps } from 'src/types';
const ReadOnlyForm1 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    borderRadius: `24px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    width: '100%',
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `16px 0px`,
    boxSizing: `border-box`,
    height: 'auto',
});
const ReadOnlyFormItem1 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `0px`,
}));
const Line3 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem2 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line12 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem3 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    margin: `12px 0px 0px 0px`,
}));
const Line4 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem4 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line5 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem5 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line6 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem6 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line7 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem7 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line8 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem8 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line9 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem9 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line10 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem10 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
const Line11 = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    alignSelf: `stretch`,
    height: `0px`,
    margin: `12px 0px 0px 0px`,
});
const ReadOnlyFormItem11 = styled(ReadOnlyFormItem)(({ theme }) => ({
    alignSelf: `stretch`,
    height: `22px`,
    margin: `12px 0px 0px 0px`,
}));
function ReadOnlyForm(props) {
    return (React.createElement(ReadOnlyForm1, { className: props.className },
        React.createElement(ReadOnlyFormItem1, null),
        React.createElement(Line3, null),
        React.createElement(ReadOnlyFormItem2, null),
        React.createElement(Line12, null),
        React.createElement(ReadOnlyFormItem3, null),
        React.createElement(Line4, null),
        React.createElement(ReadOnlyFormItem4, null),
        React.createElement(Line5, null),
        React.createElement(ReadOnlyFormItem5, null),
        React.createElement(Line6, null),
        React.createElement(ReadOnlyFormItem6, null),
        React.createElement(Line7, null),
        React.createElement(ReadOnlyFormItem7, null),
        React.createElement(Line8, null),
        React.createElement(ReadOnlyFormItem8, null),
        React.createElement(Line9, null),
        React.createElement(ReadOnlyFormItem9, null),
        React.createElement(Line10, null),
        React.createElement(ReadOnlyFormItem10, null),
        React.createElement(Line11, null),
        React.createElement(ReadOnlyFormItem11, null)));
}
export default ReadOnlyForm;
//# sourceMappingURL=ReadOnlyForm.js.map