/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import UntitledDesign3RemovImage from 'src/assets/images/Menu_Untitled_design__3__removebg_preview_1.png';
import K21Image from 'src/assets/images/Menu_K__2__1.png';
import Ellipse2Image from 'src/assets/images/Menu_Ellipse_2.png';
import HeroiconsOutlineElliImage from 'src/assets/images/Menu_heroicons_outline_ellipsis_horizontal.svg';
import { styled } from '@mui/material/styles';
import MenuItem from 'src/components/MenuItem/MenuItem';
import { MenuProps } from 'src/types';
const Menu1 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(255, 255, 255, 1)`,
    border: `1px solid rgba(241, 243, 245, 1)`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    height: `1024px`,
    width: '100%',
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
}));
const Frame12 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    flex: `1`,
    margin: `0px`,
});
const Frame61 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
const Logo = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `32px 0px 0px 40px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame60 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const UntitledDesign3Remov = styled('img')({
    height: `40px`,
    width: `134.23px`,
    objectFit: `cover`,
    margin: `0px 0px 0px 14px`,
});
const K21 = styled('img')({
    height: `60px`,
    width: `180px`,
    objectFit: `cover`,
    margin: `0px`,
});
const Frame11 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `48px 0px 0px 0px`,
});
const Menu2 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 0px 0px 48px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const MenuItem1 = styled(MenuItem)(({ theme }) => ({
    margin: `0px`,
}));
const MenuItem2 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const MenuItem3 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const MenuItem4 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const MenuItem5 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const MenuItem6 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const MenuItem7 = styled(MenuItem)(({ theme }) => ({
    margin: `24px 0px 0px 0px`,
}));
const Frame121 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `48px 0px 0px 0px`,
});
const Menu3 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 0px 0px 48px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const MenuItem8 = styled(MenuItem)(({ theme }) => ({
    margin: `0px`,
}));
const UserAccount = styled('div')({
    border: `1px solid rgba(241, 243, 245, 1)`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `space-between`,
    alignItems: `center`,
    padding: `32px 40px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `32px 0px 0px 0px`,
});
const Frame9 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Ellipse2 = styled('img')({
    height: `40px`,
    width: `40px`,
    objectFit: `cover`,
    margin: `0px`,
});
const Frame7 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px 0px 0px 14px`,
});
const VashonG = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Partner = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(173, 181, 189, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `13px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `18px`,
    textTransform: `none`,
    margin: `2px 0px 0px 0px`,
}));
const HeroiconsOutlineElli = styled('img')({
    height: `auto`,
    width: `24px`,
    margin: `0px`,
});
function Menu(props) {
    return (React.createElement(Menu1, { className: props.className },
        React.createElement(Frame12, null,
            React.createElement(Frame61, null,
                React.createElement(Logo, null,
                    React.createElement(Frame60, null,
                        false && (React.createElement(UntitledDesign3Remov, { src: UntitledDesign3RemovImage, loading: "lazy", alt: 'Untitled_design__3_-removebg-preview 1' })),
                        React.createElement(K21, { src: K21Image, loading: "lazy", alt: 'K_(2) 1' }))),
                React.createElement(Frame11, null,
                    React.createElement(Menu2, null,
                        React.createElement(MenuItem1, null),
                        React.createElement(MenuItem2, null),
                        React.createElement(MenuItem3, null),
                        React.createElement(MenuItem4, null),
                        React.createElement(MenuItem5, null),
                        React.createElement(MenuItem6, null),
                        React.createElement(MenuItem7, null)))),
            React.createElement(Frame121, null,
                React.createElement(Menu3, null,
                    React.createElement(MenuItem8, null)))),
        React.createElement(UserAccount, null,
            React.createElement(Frame9, null,
                React.createElement(Ellipse2, { src: Ellipse2Image, loading: "lazy", alt: 'Ellipse 2' }),
                React.createElement(Frame7, null,
                    React.createElement(VashonG, null, `Vashon G.`),
                    React.createElement(Partner, null, `Partner`))),
            React.createElement(HeroiconsOutlineElli, { src: HeroiconsOutlineElliImage, loading: "lazy", alt: 'heroicons-outline/ellipsis-horizontal' }))));
}
export default Menu;
//# sourceMappingURL=Menu.js.map