/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import TopographyImage from 'src/assets/images/Miles_Topography.png';
import HeroiconsMiniSparkleImage from 'src/assets/images/Miles_heroicons_mini_sparkles.svg';
import { styled } from '@mui/material/styles';
import { MilesProps } from 'src/types';
const Miles1 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(255, 255, 255, 1)`,
    border: `1px solid rgba(241, 243, 245, 1)`,
    borderRadius: `24px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    width: '100%',
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `24px`,
    boxSizing: `border-box`,
    height: 'auto',
}));
const Topography = styled('img')({
    height: `150px`,
    width: `352px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
const Frame180 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `space-between`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
const Frame92 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame187 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Frame189 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(251, 244, 235, 1)`,
    borderRadius: `100px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `6px`,
    boxSizing: `border-box`,
    margin: `0px`,
}));
const HeroiconsMiniSparkle = styled('img')({
    height: `auto`,
    width: `15px`,
    margin: `0px`,
});
const Miles2 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
}));
const Get2MilesPer1Spent = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(173, 181, 189, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `13px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `18px`,
    textTransform: `none`,
    margin: `4px 0px 0px 0px`,
}));
const Q6178 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `600`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Frame181 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-end`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `20px 0px 0px 0px`,
});
const Rectangle19 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `23px`,
    margin: `0px`,
}));
const Rectangle20 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle21 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `10px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle22 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `4px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle23 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `26px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle24 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `1px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle25 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `1px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle26 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `40px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle27 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle28 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `10px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle29 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle30 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `23px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle31 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `8px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle32 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `1px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle33 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `26px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle34 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `13px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle35 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `32px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle36 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle37 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `8px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle38 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `4px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle39 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle40 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `26px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle41 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `8px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle42 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `1px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle43 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `20px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle44 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `8px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle45 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `32px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle46 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `26px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle47 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `8px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle48 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `32px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle49 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `12px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
const Rectangle50 = styled('div')(({ theme }) => ({
    backgroundColor: `rgba(225, 163, 92, 1)`,
    borderRadius: `1px 1px 0px 0px`,
    width: `5px`,
    height: `26px`,
    margin: `0px 0px 0px 4.650000095367432px`,
}));
function Miles(props) {
    return (React.createElement(Miles1, { className: props.className },
        React.createElement(Topography, { src: TopographyImage, loading: "lazy", alt: 'Topography' }),
        React.createElement(Frame180, null,
            React.createElement(Frame92, null,
                React.createElement(Frame187, null,
                    React.createElement(Frame189, null,
                        React.createElement(HeroiconsMiniSparkle, { src: HeroiconsMiniSparkleImage, loading: "lazy", alt: 'heroicons-mini/sparkles' })),
                    React.createElement(Miles2, null, `Miles`)),
                React.createElement(Get2MilesPer1Spent, null, `Get 2 miles per $1 spent`)),
            React.createElement(Q6178, null, `6,178`)),
        React.createElement(Frame181, null,
            React.createElement(Rectangle19, null),
            React.createElement(Rectangle20, null),
            React.createElement(Rectangle21, null),
            React.createElement(Rectangle22, null),
            React.createElement(Rectangle23, null),
            React.createElement(Rectangle24, null),
            React.createElement(Rectangle25, null),
            React.createElement(Rectangle26, null),
            React.createElement(Rectangle27, null),
            React.createElement(Rectangle28, null),
            React.createElement(Rectangle29, null),
            React.createElement(Rectangle30, null),
            React.createElement(Rectangle31, null),
            React.createElement(Rectangle32, null),
            React.createElement(Rectangle33, null),
            React.createElement(Rectangle34, null),
            React.createElement(Rectangle35, null),
            React.createElement(Rectangle36, null),
            React.createElement(Rectangle37, null),
            React.createElement(Rectangle38, null),
            React.createElement(Rectangle39, null),
            React.createElement(Rectangle40, null),
            React.createElement(Rectangle41, null),
            React.createElement(Rectangle42, null),
            React.createElement(Rectangle43, null),
            React.createElement(Rectangle44, null),
            React.createElement(Rectangle45, null),
            React.createElement(Rectangle46, null),
            React.createElement(Rectangle47, null),
            React.createElement(Rectangle48, null),
            React.createElement(Rectangle49, null),
            React.createElement(Rectangle50, null))));
}
export default Miles;
//# sourceMappingURL=Miles.js.map