/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import { styled } from '@mui/material/styles';
import { SecureCodeProps } from 'src/types';
const SecureCode1 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    height: 'auto',
    width: 'fit-content',
});
const SecureCode2 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(73, 80, 87, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `13px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `18px`,
    textTransform: `none`,
    width: `320px`,
    margin: `0px`,
}));
const Frame145 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `8px 0px 0px 0px`,
});
const Input1 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px`,
});
const Q7 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Input2 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px 0px 0px 8px`,
});
const Q8 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Input3 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px 0px 0px 8px`,
});
const Q0 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(222, 226, 230, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Input4 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px 0px 0px 8px`,
});
const Q01 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(233, 236, 239, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Input5 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px 0px 0px 8px`,
});
const Q02 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(233, 236, 239, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
const Input6 = styled('div')({
    border: `1px solid rgba(233, 236, 239, 1)`,
    boxSizing: `border-box`,
    borderRadius: `20px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `10px 14px`,
    width: `56px`,
    margin: `0px 0px 0px 8px`,
});
const Q03 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(233, 236, 239, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `30px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `36px`,
    textTransform: `none`,
    margin: `0px`,
}));
function SecureCode(props) {
    return (React.createElement(SecureCode1, { className: props.className },
        React.createElement(SecureCode2, null, `Secure Code`),
        React.createElement(Frame145, null,
            React.createElement(Input1, null,
                React.createElement(Q7, null, `7`)),
            React.createElement(Input2, null,
                React.createElement(Q8, null, `8`)),
            React.createElement(Input3, null,
                React.createElement(Q0, null, `0`)),
            React.createElement(Input4, null,
                React.createElement(Q01, null, `0`)),
            React.createElement(Input5, null,
                React.createElement(Q02, null, `0`)),
            React.createElement(Input6, null,
                React.createElement(Q03, null, `0`)))));
}
export default SecureCode;
//# sourceMappingURL=SecureCode.js.map