/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
/// <reference types="react" />
import { Graph1LineProps } from 'src/types';
declare function Graph1Line(props: Graph1LineProps): JSX.Element;
export default Graph1Line;
//# sourceMappingURL=Graph1Line.d.ts.map