/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import React from 'react';
import { styled } from '@mui/material/styles';
import Checkbox1 from 'src/components/Checkbox1/Checkbox1';
import { CheckboxItemProps } from 'src/types';
const StateUnchecked = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    height: 'auto',
    width: 'fit-content',
});
const Frame2 = styled('div')({
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px`,
});
const Checkbox2 = styled(Checkbox1)(({ theme }) => ({
    width: `16px`,
    height: `16px`,
    margin: `0px`,
}));
const Checkbox3 = styled('div')(({ theme }) => ({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(33, 37, 41, 1)`,
    fontStyle: `normal`,
    fontFamily: `Inter`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 12px`,
}));
function CheckboxItem(props) {
    return (React.createElement(StateUnchecked, { className: props.className },
        React.createElement(Frame2, null,
            React.createElement(Checkbox2, null),
            React.createElement(Checkbox3, null, `Checkbox`))));
}
export default CheckboxItem;
//# sourceMappingURL=CheckboxItem.js.map