/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse1Image from 'src/assets/images/FeaturedOffer_Ellipse_1.png';
import { styled } from '@mui/material/styles';
import { FeaturedOfferProps } from 'src/types';

const FeaturedOffer1: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  boxSizing: `border-box`,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `center`,
  alignItems: `center`,
  padding: `24px`,
  height: 'auto',
});

const Ellipse1: any = styled('img')({
  height: `60px`,
  width: `60px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Frame46: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const Q50OffOnSubscription: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px`,
}));

const SeeAllHboCoupons: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(134, 142, 150, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `4px 0px 0px 0px`,
}));

const Q5StockBack: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 140, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `20px 0px 0px 0px`,
}));

function FeaturedOffer(props: FeaturedOfferProps): JSX.Element {
  return (
    <FeaturedOffer1 className={props.className}>
      <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
      <Frame46>
        <Q50OffOnSubscription>
          {`50% off on subscriptions`}
        </Q50OffOnSubscription>
        <SeeAllHboCoupons>{`See all HBO coupons`}</SeeAllHboCoupons>
      </Frame46>
      <Q5StockBack>{`5% stock back`}</Q5StockBack>
    </FeaturedOffer1>
  );
}

export default FeaturedOffer;
